---
metadata:
  name: New volunteer guide
  short_name: Guide
  description: New volunteer guide - welcome to Warwick University Unit
  language: en
  pathPrefix: "/"
  siteImage:
  favicon: "/assets/favicon.png"
  themeColor: "#ff0000"
header:
  enabled: true
  logo: "/assets/favicon.png" 
  logoLink: "/"
  helpUrl: ""
  links:
    - text: Main site
      link: https://warwickfirstaid.co.uk
      external: true
sidebar:
  enabled: true
  forcedNavOrder:
    - "/ourunit"
    - "/events"
    - "/uniform"
    - "/it"
    - "/general"
    - "/support"
  # expanded:
  groups:
    - order: 1
      path: "/ourunit"
      title: ":green_heart: Our Unit"
    - order: 2
      path: "/events"
      title: ":ambulance: Events"
    - order: 3
      path: "/uniform"
      title: ":shirt: Uniform"
    - order: 4
      path: "/it"
      title: ":computer: IT Systems"
    - order: 5
      path: "/general"
      title: ":pushpin: General information"
    - order: 6
      path: "/support"
      title: ":yellow_heart: Support"
        #links:
        #    - text: BooGi
        #      link: https://github.com/filipowm/boogi
        #    - text: React
        #      link: https://reactjs.org
  ignoreIndex: false
    #  poweredBy:
    #    trademark: "/assets/gatsby.png"
    #    name: GatsbyJS
    #    link: https://www.gatsbyjs.org
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: "/assets/favicon.png"

social:
  facebook: https://www.facebook.com/groups/warwickfirstaid
  twitter: https://twitter.com/warwickfirstaid

features:
  darkMode:
    enabled: true  
    default: false
  editOnRepo:
    location: https://github.com/filipowm/boogi 
    type: github
    editable: false
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: false
    includePaths:
      - "/configuration/settingup/features"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: false
    title: BooGi Docs
    showIcon: false
    copyright: "2020, Mateusz Filipowicz"
    webMaster: "Mateusz Filipowicz"
    managingEditor: "Mateusz Filipowicz"
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "boogi"
  scrollTop: true
  search:
    enabled: true
    engine: 'algolia'
    indexName: '${algolia_index}'
    algoliaAppId: '${algolia_appid}'
    algoliaSearchKey: '${algolia_search}'
    algoliaAdminKey: '${algolia_admin}'
    placeholder: 'Search'
    startComponent: 'input' # icon
    excerptSize: 8000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode: 
    enabled: false
    hideHeader: true
    hideToc: true
    hideSidebar: true
